<h4>Numpy assignment#1<h4>

In [35]:
import pandas as pd
import numpy as np

In [36]:
a = np.array([1,2,3,4])
b = np.array([[1,2,3,4],[5,6,7,8]])
c = np.array([5])
print(a)

[1 2 3 4]


In [37]:
print(b)

print ("------------------------------")

print(c)

[[1 2 3 4]
 [5 6 7 8]]
------------------------------
[5]


In [38]:
c = np.zeros(c)
print(c)

[0. 0. 0. 0. 0.]


In [39]:
a= np.ones(a)
print(a)

[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]]


In [40]:
f = np.array([1,2,3,4])
g = np.array([5,6,7,8])
h = np.array([5,8,9,8])

x = f + g
print(x)

y = f * g
print(y)

x = h - f
print(x)

y = f / h
print(y)



[ 6  8 10 12]
[ 5 12 21 32]
[4 6 6 4]
[0.2        0.25       0.33333333 0.5       ]


In [41]:
x = np.sqrt(x)
print(x)

[2.         2.44948974 2.44948974 2.        ]


In [42]:
y = np.exp(y)
print(y)

[1.22140276 1.28402542 1.39561243 1.64872127]


In [43]:
h = np.log(h)
print(h)

[1.60943791 2.07944154 2.19722458 2.07944154]


In [44]:
h = np.arange(1,13).reshape(3,4)
print(h)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [45]:
i = h.ravel() #flattening 
print(i)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [46]:
j = h.T
print(j)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [47]:
#b= np.eye(b)
#print(b)

#b = np.arange(b)
#c = np.linespace(c)
#print(b)
#print(c)

In [48]:
h[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [49]:
m = np.array([1,2,4,6,8,2])
mean = np.mean(m)
print(mean)

3.8333333333333335


In [50]:
median = np.median(m)
print(median)

3.0


In [51]:
std = np.std(m)
print(std)

2.4776781245530843


In [52]:
var = np.var(m)
print(var)

6.138888888888888


In [53]:
#mod = np.mod(m)
#print(mod)

In [54]:
sum = np.sum(m)
print(sum)

23


In [55]:
n = np.array([[2,3], [5,6]])
o = np.array([[5,6], [2,3]])
p = np.dot(n, o)
print(p)


[[16 21]
 [37 48]]


In [56]:
det = np.linalg.det(n)
inv = np.linalg.inv(o)

print(det)

print("------------------")
 
print(inv)

-2.9999999999999982
------------------
[[ 1.         -2.        ]
 [-0.66666667  1.66666667]]


In [57]:
np.save('array.npy', n )

<h4>Scenario base assignment#2 of numpy<h4>

In [58]:
# Sample data
Sales = np.array([100, 150, 200, 175, 130, 90, 220, 160, 140, 180, 210, 190, 230, 120, 110, 240, 130, 250, 140, 180, 220, 190, 210, 200, 160, 170, 190, 200, 180, 210])

# Total sales
totalsales = np.sum(Sales)

# Average sales
averagesales = np.mean(Sales)

# Day with highest sales
day_with_highest_sales = np.argmax(Sales) + 1  # Adding 1 to match day count

totalsales, averagesales, day_with_highest_sales


(5275, 175.83333333333334, 18)

<h4>Weather Data Processing<h4>

In [68]:
# Sample data
temp= np.array([
    [70, 75, 80, 72, 68, 74, 47],
    [51, 76, 81, 73, 65, 75, 78],
    [72, 47, 82, 74, 70, 66, 29]
])

# Average temperature for each day across all weeks
average_temp_per_day = np.mean(temp, axis=0)

average_temp_per_day


array([64.33333333, 66.        , 81.        , 73.        , 67.66666667,
       71.66666667, 51.33333333])

<h4>Financial Analysis<h4>

In [71]:
# Sample data
prices = np.array([100, 102, 104, 103, 105, 107, 106, 117, 116, 118, 120, 119, 121,129, 130, 131])

# Monthly return
monthlyreturn = (prices[-1] - prices[0]) / prices[0] * 100

monthlyreturn


31.0

<h4>Student Grades Analysis<h4>

In [72]:
# Sample data
Grades = np.array([
    [85, 90, 88],
    [88, 82, 80],
    [88, 89, 99],
    [87, 91, 67]
])

# Average grade for each student
average_grade_per_student = np.mean(Grades, axis=1)

# Overall class average for each subject
class_average_per_subject = np.mean(Grades, axis=0)

average_grade_per_student, class_average_per_subject


(array([87.66666667, 83.33333333, 92.        , 81.66666667]),
 array([87. , 88. , 83.5]))

<h4>  Image Processing <h4>

In [74]:
# Sample data (3x3 grayscale image)
images = np.array([
    [0, 128, 255],
    [44, 182, 138],
    [255, 54, 0]
])

# Normalize pixel values to range 0 to 1
normalized_image = images / 255.0

normalized_image


array([[0.        , 0.50196078, 1.        ],
       [0.17254902, 0.71372549, 0.54117647],
       [1.        , 0.21176471, 0.        ]])

<h4>Population Growth Analysis<h4>

In [75]:
# Sample data
population = np.array([1600, 1750, 1900, 2100, 2300 , 1000, 1100, 1200, 1300, 1450])

# Annual growth rate
annualgrowthrate = np.diff(population) / population[:-1] * 100

# Year with highest growth
yearwithhighestgrowth = np.argmax(annualgrowthrate) + 1  # Adding 1 to match year count

annualgrowthrate, yearwithhighestgrowth


(array([  9.375     ,   8.57142857,  10.52631579,   9.52380952,
        -56.52173913,  10.        ,   9.09090909,   8.33333333,
         11.53846154]),
 9)

<h4>Traffic Data Analysis<h4>

In [78]:
# Sample data (7 days, 24 hours)
trafic = np.random.randint(50, 200, size=(7, 24))

# Total traffic for each day
total_trafic_per_day = np.sum(trafic, axis=1)

# Busiest hour of the week
busiesthour_of_week = np.argmax(np.sum(trafic, axis=0))

total_trafic_per_day, busiesthour_of_week


(array([2880, 3236, 3214, 3471, 3145, 2678, 3302]), 17)

<h4> Product Inventory Management <h4>

In [81]:
# Sample data
stock_levels = np.array([45, 60, 70, 35, 50, 20])

# Reorder products with stock levels below threshold (50 units)
reorder_list = np.where(stock_levels < 50)[0]

reorder_list


array([0, 3, 5], dtype=int64)

<h4> Game Score Analysis <h4>

In [89]:
# Sample data (5 players, 10 rounds)
scores = np.random.randint(60, 300, size=(5, 20))

# Player with highest average score
highest_avg_scoreplayer = np.argmax(np.mean(scores, axis=1))

# Round with highest total score
highest_total_scoreround = np.argmax(np.sum(scores, axis=0))

highest_avg_scoreplayer, highest_total_scoreround


(2, 15)

<h4>Financial Portfolio Analysis<h4>

In [87]:
# Sample data (4 assets, 30 days)
Return = np.random.randn(6, 40)

# Portfolio's overall daily return
overall_daily_return = np.mean(Return, axis=0)

# Asset with highest volatility
highest_volatility_asset = np.argmax(np.std(Return, axis=1))

overall_daily_return, highest_volatility_asset


(array([-0.37400034, -0.13834732, -0.25340594,  0.1969485 ,  0.48998821,
        -0.28875171,  0.43229123,  0.812748  , -0.39140937, -0.25029433,
         0.06569314, -0.20512144, -1.01093442, -0.29306322,  0.49125925,
         0.23890732,  0.13456702,  0.62766997,  0.51159061,  0.19655007,
         0.36619   ,  0.15030024,  0.62222441, -0.14723008, -0.25230876,
         0.07425074,  0.73445854,  0.15895881,  0.19503446,  0.02158909,
        -0.18219967,  0.45759241,  0.05158143, -0.08580633,  0.54963973,
         0.00320629,  0.72474852,  0.35345426,  0.56651317,  0.00427387]),
 0)