In [77]:
import pandas as pd
import numpy as np

In [78]:
a = np.array([1,2,3,4])
b = np.array([[1,2,3,4],[5,6,7,8]])
c = np.array([5])
print(a)

[1 2 3 4]


In [79]:
print(b)

print ("------------------------------")

print(c)

[[1 2 3 4]
 [5 6 7 8]]
------------------------------
[5]


In [80]:
c = np.zeros(c)
print(c)

[0. 0. 0. 0. 0.]


In [81]:
a= np.ones(a)
print(a)

[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]]


In [95]:
f = np.array([1,2,3,4])
g = np.array([5,6,7,8])
h = np.array([5,8,9,8])

x = f + g
print(x)

y = f * g
print(y)

x = h - f
print(x)

y = f / h
print(y)



[ 6  8 10 12]
[ 5 12 21 32]
[4 6 6 4]
[0.2        0.25       0.33333333 0.5       ]


In [98]:
x = np.sqrt(x)
print(x)

[2.         2.44948974 2.44948974 2.        ]


In [99]:
y = np.exp(y)
print(y)

[1.22140276 1.28402542 1.39561243 1.64872127]


In [104]:
h = np.log(h)
print(h)

[1.60943791 2.07944154 2.19722458 2.07944154]


In [111]:
h = np.arange(1,13).reshape(3,4)
print(h)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [114]:
i = h.ravel() #flattening 
print(i)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [116]:
j = h.T
print(j)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [122]:
#b= np.eye(b)
#print(b)

#b = np.arange(b)
#c = np.linespace(c)
#print(b)
#print(c)

In [126]:
h[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [132]:
m = np.array([1,2,4,6,8,2])
mean = np.mean(m)
print(mean)

3.8333333333333335


In [133]:
median = np.median(m)
print(median)

3.0


In [135]:
std = np.std(m)
print(std)

2.4776781245530843


In [139]:
var = np.var(m)
print(var)

6.138888888888888


In [142]:
#mod = np.mod(m)
#print(mod)

In [143]:
sum = np.sum(m)
print(sum)

23


In [147]:
n = np.array([[2,3], [5,6]])
o = np.array([[5,6], [2,3]])
p = np.dot(n, o)
print(p)


[[16 21]
 [37 48]]


In [152]:
det = np.linalg.det(n)
inv = np.linalg.inv(o)

print(det)

print("------------------")
 
print(inv)

-2.9999999999999982
------------------
[[ 1.         -2.        ]
 [-0.66666667  1.66666667]]


In [154]:
np.save('array.npy', n )